#!/usr/bin/env python3

from oregano import Deployment, nomad

acs = '10.42.2.1'

dep = Deployment(__name__)

dep.add(nomad.Provider, f'http://{acs}:4646')
dep.add(nomad.Job, jobspec='templates/vmck.nomad')
dep.add(nomad.Job, jobspec='templates/interface.nomad')

if __name__ == '__main__':
    dep.cli()
