#!/usr/bin/env python3

from oregano import Deployment, consul, nomad

acs = '10.42.2.1'

dep = Deployment(__name__, backend=consul.Backend(f'{acs}:8500'))

dep.add(nomad.Provider, f'http://{acs}:4646')
dep.add(nomad.Job, template='vmck.nomad')
dep.add(nomad.Job, template='interface.nomad')

if __name__ == '__main__':
    dep.cli()
