#!/usr/bin/env python3

from pathlib import Path
from oregano import terraform, nomad, cli

path = Path(__file__).resolve().parent
templates = path / 'templates'

config = terraform.Configuration(path / 'tf')
config.add(nomad.Provider('http://10.42.2.1:4646'))

interface = nomad.Job('acs-interface', jobspec=templates / 'interface.nomad')
config.add(interface)

if __name__ == '__main__':
    cli.main(config)
