{
 "title": "ACS Interface",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Individual Running Submissions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nomad_nomad_job_summary_running{exported_job=~\"vmck-.*\",task_group=\"test\"} > 0"
    }
   ]
  },
  {
   "title": "Running Submissions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nomad_nomad_job_summary_running{exported_job=~\"vmck-.*\",task_group=\"test\"} > 0)"
    }
   ]
  },
  {
   "title": "Queued Submissions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(nomad_nomad_job_summary_queued{exported_job=~\"vmck-.*\",task_group=\"test\"} > 0)"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_memory_rss{exported_job=~\"vmck@.*\", task=\"vm\"})"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_cpu_total_percent{exported_job=~\"vmck@.*\", task=\"vm\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "avg(nomad_client_host_cpu_total{host=\"vmchecker-compute.cs.pub.ro\"})/100"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 14 },
   "targets": [
    {
     "expr": "nomad_client_host_memory_used{host=\"vmchecker-compute.cs.pub.ro\"}/nomad_client_host_memory_total{host=\"vmchecker-compute.cs.pub.ro\"}"
    }
   ]
  },
  {
   "title": "Memory Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 14 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "nomad_client_host_memory_total{host=\"vmchecker-compute.cs.pub.ro\"}"
    }
   ]
  }
 ]
}